### ISSUE TITLE
Decide Topic - Industry_Project

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#1]
# 지금까지 나온 주제는
---

### 버스 승객 모니터링
* 효과 : 승객의 수와 탑승 시간대를 이용하여 버스 노선을 개편할 때, 이용할 수 있다.
### 가계부 모니터링
* 최근의 지출과 과거를 비교하여, 어느 부분에서 더 나갔고 덜 나갔는지 알아내어 알려줄 수 있다.
### 인바디 데이터 모니터링
* 현재 인바디 데이터와 최신 인바디 데이터를 비교하여, 앞으로 어떤 부분이 필요한지 알려줄 수 있다.
### 주식 모니터링
* 어떤 사건이 터지거나 시간이 지나면 주식의 그래프가 어떤 식으로 움직일지 예측할 수 있다.
### 건물 출입시 마스크 착용 여부 모니터링
* 건물을 출입하는 사람들의 마스크 착용 비율로 코로나 확진자의 감소가 면연력과 마스크 착용중 어느 부분이 더 큰지 알 수 있다.
### 병원에서 환자 모니터링
* 밤이나 새벽 시간대에 환자의 몸에 이상이 생기면, 즉시 간호사와 의사에게 알려줄 수 있다.
### 교실 내부 카메라로 학생들 모니터링
* 학생들이 제대로 집중하고 듣는지 알 수 있다.
### 무인가게 CCTV
* 절도 사건 발생 시에, 예상이 되는 시간대를 제공할 수 있다.

---
# 등이 있고, 여기다가 각자 추가해주면 되고, 주제는 주말에 오프라인으로 모여서 정합시다.

**Comment by ByeongJun-Jang** [comment]
상용적인 측면으로 보면 가계부, 주식, 마스크 여부가 좋을 것 같은데

**Comment by ByeongJun-Jang** [comment]
차별성 측면으로 생각하면 가계부 모니터링을 초점으로 올바른 지출 생활을 할 수 있게 도와주는 느낌으로도 괜찮을 거 같은데

**Comment by Hong-JinSuk** [comment]
아니면 주식 차별성으로 개인적인 생각에 기반해서 추천해주는 느낌도 괜찮을듯. 예를 들면 특정 뉴스가 나왔을 때, 그 뉴스만을 반영해서 어느 섹터가 괜찮을지 같은 느낌?

**Comment by Hong-JinSuk** [comment]
아니면 모니터링이니깐 추천시스템도 괜찮을듯

**Comment by Hong-JinSuk** [comment]
아니면 핸드폰 이용자 위치에 따른 주변 먹거리 추천?
이용자 위치를 계속 모니터링하면서 주변에서 시간대별로 추천해주는 식으로 해주는 것도 괜찮을듯

**Comment by kgeunwo77** [comment]
자녀 컴퓨터 사용시간 제한 프로그램처럼 컴퓨터 사용 현황을 모니터링해서 정해진 시간만 사용할 수 있게 하는 프로그램 괜찮을듯

**Comment by kgeunwo77** [comment]
컴퓨터가 켜진 시간 전체를 다루는 기존 프로그램과 달리, 프로그램 별로 cpu 사용을 체크해서 지정한 게임 앱이 실행될 때만 시간이 차감되도록 하는 방식을 차별성으로 생각하면 될 거 같다
