### ISSUE TITLE
9주차 이후 개발 일정

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#10]
현재 각자 맡은 부분 합해보면 로그인/회원가입 UI, 사용시간 관리 파일 입출력, CPU와 메모리 사용량으로 프로세스 실행 중인지 확인 인데, 9주차까지 각자 파트 완료하고 통합하는 걸 목표로 하겠습니다

그리고 10주차부터는 기능들이 잘 통합되어 실행되는지 확인하고 이후 알림 기능 등을 추가하거나 UI를 다듬어야할 거 같은데 아이디어 있으면 알려주세요. 참고로 14주차 안으로 마무리해야합니다

**Comment by Hong-JinSuk** [comment]
일단 9주차에 각자 파트를 가져와서 간단하게 합쳐보고 어느정도 해야될지 그때 의논해볼까요??

**Comment by ByeongJun-Jang** [comment]
> 일단 9주차에 각자 파트를 가져와서 간단하게 합쳐보고 어느정도 해야될지 그때 의논해볼까요??

네, 제가 맡은 부분 마저 마무리해서 pyscript를 사용해 합치는 것을 목표로 하죠
