### ISSUE TITLE
로그인 및 회원가입 UI에 관하여

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#13]
<img width="546" alt="스크린샷 2022-11-12 오후 10 13 08" src="https://user-images.githubusercontent.com/85213981/201475765-263e4c59-85b7-4142-9e2a-8311b90fba50.png">
<img width="635" alt="스크린샷 2022-11-12 오후 10 13 21" src="https://user-images.githubusercontent.com/85213981/201475772-b96f348b-8bfd-4add-b46b-341551931b59.png">
<br>
위 사진과 같이 회원가입 관련 form으로 이동 후 로그인 switch 폼에 가려지는 이슈가 발생 <br>
현 상황으론 css 파일의 너비 관련 해 문제가 발생하였다고 생각합니다.

**Comment by Hong-JinSuk** [comment]
switch폼에 가려지는 이슈가 뭐죠??

**Comment by ByeongJun-Jang** [comment]
> switch폼에 가려지는 이슈가 뭐죠??

현재 로그인 및 회원가입 페이지의 유저 인터페이스는 로그인, 회원가입 폼 / 스위치 폼으로 이루어져 있습니다. 스위치 폼은 위 사진에 보이듯이 정보 입력 폼이 아닌 클릭으로 로그인 혹은 회원가입 폼을 불러오는 것입니다.

**Comment by kgeunwo77** [comment]
css 파일의 너비를 조정하면 해결되는 문제인가요?? 너비를 줄여서 한 화면에 두 개의 폼 모두 보이게 하면 해결될까요?

**Comment by ByeongJun-Jang** [comment]
<img width="961" alt="스크린샷 2022-11-17 오후 8 29 06" src="https://user-images.githubusercontent.com/85213981/202434918-e5481c65-6946-4dce-9910-a1c4c73cc6f0.png">
<img width="961" alt="스크린샷 2022-11-17 오후 8 29 21" src="https://user-images.githubusercontent.com/85213981/202434953-9174089d-9071-42e2-b3cb-510947484c6c.png">
<br>
해당 문제사항은 로그인 회원가입에 해당하는 css 파일의 width 조정을 하면 해결되는 문제였습니다. <br> 문제가 해결되었으니 이슈는 닫겠습니다.
