### ISSUE TITLE
코드 병합 및 연동일정 조율

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#14]
DB 시험이 11월 24일인데, 코드 병합은 28일날 해보는게 어떨까요??
11월 마지막 주에 코드 병합이랑 오류 수정하고, 그 다음에 코드 연동 일주일정도 해보면 될 것 같습니다.

**Comment by kgeunwo77** [comment]
가능합니다 28일 좋습니다! 그때 코드 병합하고 병합 시 발생하는 오류 수정을 목표로 활동 진행하면 될 것 같습니다

**Comment by ByeongJun-Jang** [comment]
네 전에 개발일정 작성했던 것처럼 진행하면 좋을 것 같습니다

**Comment by Hong-JinSuk** [comment]
그럼 저 일정대로 하는 것으로 하겠습니다.
