### ISSUE TITLE
Peer-Review 답변에 관하여

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#15]
<h2>Anti-S Team에서 PR 답변에 관하여 말하고자 합니다.</h2>
<br><h3>관련된 의논하고자 하는 점 말씀해주세요.</h3>

**Comment by kgeunwo77** [comment]
평가 계획에 대해 어떤 방식으로 평가할 것인지 궁금하다고 comment가 들어왔는데,
1. cpu 및 메모리 사용률을 보고 게임 프로세스가 실행 중인지 옳게 판단하는가
2. 차별성 입증을 위해 게임 이외의 프로세스도 적용이 가능한가
이렇게 두 가지 하려고 하는데 어떤가요

**Comment by Hong-JinSuk** [comment]
프로그램의 안정성과 사용자가 작업 관리자를 사용하여 프로그램을 강제종료 시키는 것에 대해 대처할 것인지 질문이 들어왔습니다. 이에 대한 해결 방안으로는

    1.  방화벽에 걸리는 것에 대해서는 관리자 권한으로 실행되게 만들어보면 어떨까 싶다.
    2.  작업 관리자의 경우 윈도우 환경에서는 제어가 가능하므로 문제가 되지 않을 것 같다.

으로 할까합니다.

**Comment by ByeongJun-Jang** [comment]
프로젝트 목표관련해서 유튜브, 웹툰 등의 처리방안은 어쩔 것인지 질문을 받았는데, 이에 관한 답변은  
</hr>
  
1. 프로젝트의 차별성 관련으로 컴퓨터 사용의 문제가 아닌 게임 이용이 문제라는 것을 강조해야 할 것 같습니다.
2. 게임 이용 범위는 프로세스 상 확인이 가능한 것을 강조해야 할 것 같습니다.

**Comment by ByeongJun-Jang** [comment]
이상 pr 관련해서 토의하고자 할 점이 없어 보이기에 issue는 close하겠습니다.
