### ISSUE TITLE
프로젝트 진행과정 점검

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#16]
각자 구현하기로 한 기능에서 못한 부분이나 구현 완료한 부분 체크해서 알려주실 수 있으십니까?

**Comment by Hong-JinSuk** [comment]
저는 아래 4가지 완료했습니다.

   1. cpu 사용량
   2. memory 사용량
   3. 실행중인 process name 받아오기
   4. 실행중인 process PID 받아오기

**Comment by ByeongJun-Jang** [comment]
프론트 부분은 
  
초기 회원가입 및 로그인, 관리자 페이지까지 완료하였으며,  
사용자에게 남은 시간을 알려주는 미니ui는 아직 구현하지 못 하였습니다.

**Comment by kgeunwo77** [comment]
1. 사용자에게 할당하는 초기 시간 설정
2. 시간 사용 시 남은 시간 최신화

이렇게 완료했고 생성된 사용자별로 다르게 시간 할당하는 것, 타 파트와의 연동은 아직 구현 못했습니다
