### ISSUE TITLE
admin page에 관하여

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#17]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/85213981/204130345-67b6c429-3d1d-4c94-8d75-923de9c03c56.png">
  
<h2> 위 사진은 어드민 페이지 초안으로 만들어봤습니다.</h2> <h4>해당 페이지에 관한 내용은 간략하게 먼저 시간 선택하는 창을 우선적으로 생각하고 있습니다. 의견이 있으면 말씀해주세요.  </h4><h4>
저는 시간적 여유가 될 시, 사용자 별 시간 통계 쪽으로 생각해봤습니다.</h4>
<h5> (위의 시간 선택은 대체 이미지로 넣었습니다.) </h5>

**Comment by Hong-JinSuk** [comment]
사용자 별 시간 통계는 어떤 방식으로 시각화 할지 생각해 두신게 있으신가요?

**Comment by kgeunwo77** [comment]
유저별로 큰 버튼을 만들고, 눌렀을 때 각 유저의 시간을 조정하거나 통계를 확인할 수 있는 탭이 보여지면 좋을 것 같습니다

**Comment by ByeongJun-Jang** [comment]
말씀하신대로 각 유저 별 통계 표시를 구현하고자 했지만, 앞서 시간이 부족할 거 같기에 추후에 완성해보도록 하겠습니다.
