### ISSUE TITLE
Python & HTML 연동

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#18]
현재 Python과 HTML 연동에 문제가 있습니다.

플라스크와 PyQt중 하나를 선택해야 될 것 같은데, 다뤄본적 있으신분 계신가요??

**Comment by kgeunwo77** [comment]
일단 저는 두 가지 모두 다뤄본 적 없습니다

**Comment by ByeongJun-Jang** [comment]
플라스크가 pyflask 말씀하시는 것 같은데 기존 웹 프로그래밍 할 때 사용하는 것으로만 알고있어 경험이 없습니다

**Comment by ByeongJun-Jang** [comment]
연동이라 하시면 코드 병합 과정에서 문제같은데 남은 시간과 대조했을 때 가능성이 없어 보이는데 어떻게 생각하시는지..?

**Comment by Hong-JinSuk** [comment]
그러면 남은시간동안은 각자 구현하는걸로하고, 학기가 끝나고 방법을 찾아보는걸로 하는건 어떨까요?
