### ISSUE TITLE
cpu usage 받아오는 과정에서 딜레이 문제발생

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#19]
```python
def checkCpuUsage(PID):
    for process in psutil.process_iter():
        for pid in PID:
            if str(process.pid) == str(pid):
                print("CpuUsage of {0}({1}) : ".format(process.name(), process.pid)+str(process.cpu_percent(interval=1)))
```
코드에서 interval=1로 설정하면 1초에 1개씩 나오게 되는데, 만약에 '키워드를 포함하는 코드가 5개가 있다.' 라고 가정하면, 5개가 동시에 1초동안의 평균을 내서 나오는 것이 아닌 1초 ... 1초 ... 식으로 딜레이가 생기는데 해결할 방법이 있을까요...

**Comment by Hong-JinSuk** [comment]
CpuUsage of python3.9.exe(2388) : 0.0
1초 ...
CpuUsage of python3.9.exe(7396) : 0.0
1초...
CpuUsage of python3.9.exe(9896) : 0.0
1초...
CpuUsage of python3.9.exe(10892) : 0.0
...

이런식으로 나옵니다.

**Comment by ByeongJun-Jang** [comment]
말씀하신게 5개가 한 번에 출력되어야 하는데 그게 아니라는 것인가요??

**Comment by Hong-JinSuk** [comment]
프로세스들 usage를 받아올 때, 병렬처리로 받아와야하는데, 직렬로 받아와져서 문제가 생겼습니다.

**Comment by kgeunwo77** [comment]
반복문이기 때문에 한 개씩 직렬로 받아와지는 것이 아닐까요?
'5개가 동시에 1초 동안의 평균을 내서 나온다'는 것이 무슨 뜻인지 이해가 잘 안됩니다

**Comment by kgeunwo77** [comment]
그리고 지금처럼 직렬로 받아와서 딜레이가 생기면 시간 지연이 길어져서 문제가 되는건가요?

**Comment by Hong-JinSuk** [comment]
넵 5개가 각각 병렬로 실행되서 총 1초가 걸려야하는데, 직렬로 실행되서 총 5초가 소요됩니다.

**Comment by Hong-JinSuk** [comment]
이 건은 스레딩으로 병렬 처리를 해보도록 해보겠습니다!!
