### ISSUE TITLE
Preparation-Presentation

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#2]
# 프레젠테이션 준비 목록
### 문제
- 필요성
- Input, Output이 무엇인가?
### 해결방법
- 순서도, 동작 방식, 알고리즘 등
### 차별성
- 우리만의 특별한 점
### 예상 결과물
- 이건 아직 미정

& PPT에 쓸 사진 및 템플릿도 정해주시면 감사하겠습니다~
---
## 4가지 해결해야 됩니다~!!

**Comment by ByeongJun-Jang** [comment]
[https://slidesgo.com/ko/%ED%85%8C%EB%A7%88/%EC%8B%9C%EA%B0%84%EC%8B%9C%EA%B3%84-%EC%9D%B8%ED%8F%AC%EA%B7%B8%EB%9E%98%ED%94%BD#search-%EC%8B%9C%EA%B0%84&position-1&results-14&rs=search](url) 괜찮은 시계 테마 템플릿

**Comment by Hong-JinSuk** [comment]
![image](https://user-images.githubusercontent.com/86042721/190545298-d4bfa3e4-fe0c-43ad-b5f3-930556299167.png)
![image](https://user-images.githubusercontent.com/86042721/190844859-f978952a-1eb0-4e90-a269-0fb4a1526b96.png)

이 사진처럼 사용시간을 두는 것과 실제 사용시간을 측정하여 하는 것이 우리의 차별성!

**Comment by Hong-JinSuk** [comment]
![image](https://user-images.githubusercontent.com/86042721/190545421-278d5bea-1b03-473a-a1f1-9ea5d8197387.png)
수도코드 -> 이대로 개발할 수 있으면 깔끔할듯?

**Comment by kgeunwo77** [comment]
위에 코드처럼 -> 게임 사용 시간만 따로 측정해서 설정 시간 초과하면 아예 프로세스 강제종료
이 방법이 pc방처럼 로그인화면으로 돌리는 거보다 좋겠다 차별성 측면에서

**Comment by Hong-JinSuk** [comment]
![image](https://user-images.githubusercontent.com/86042721/190548071-03102a43-15e5-4215-b284-88a6c5540817.png)
![image](https://user-images.githubusercontent.com/86042721/190548651-dce0b0a3-9f6a-4731-a3e8-ad8a1361a1e8.png)

이 두 사진으로 국내 게임시장의 성장률과 청소년들의 게임 이용 실태를 비교하면서 문제를 들어가면 될듯!

**Comment by ByeongJun-Jang** [comment]
![11](https://user-images.githubusercontent.com/85213981/190548812-6a72e67b-1c3d-4041-9271-486f881943fe.jpg)
![22](https://user-images.githubusercontent.com/85213981/190548825-f5f88e52-8e1a-4219-a480-e390079bf53d.png)

**Comment by kgeunwo77** [comment]
http://pptbizcam.co.kr/?p=4895
발표 자료에 쓸 스톱워치 애니메이션

**Comment by Hong-JinSuk** [comment]
![10000-layers-of-legos](https://user-images.githubusercontent.com/86042721/190842197-2c40c195-993c-4d24-955d-852c3e421681.gif)
누저기간 GIF

**Comment by Hong-JinSuk** [comment]
![게임 대기화면](https://user-images.githubusercontent.com/86042721/190842743-f9c72056-30cf-4024-ac86-0817d9df89b0.PNG)
![게임 대기화면 - CPU 사용률](https://user-images.githubusercontent.com/86042721/190842744-3b5a8a5c-d2a2-4540-adce-6bc00d5d0158.PNG)
![게임 실행화면 - CPU 사용률](https://user-images.githubusercontent.com/86042721/190842745-e39af64b-0e04-42ae-8252-c5d2d63343e8.PNG)
![게임 실행화면](https://user-images.githubusercontent.com/86042721/190842746-eb0dd202-9d8f-4e49-8570-36c647d1ca89.PNG)
게임을 하는지 안하는지 알 수 있는 방법

**Comment by ByeongJun-Jang** [comment]
![55](https://user-images.githubusercontent.com/85213981/190843228-de3f688f-63e0-47a9-9aba-621b9077b102.png)

**Comment by kgeunwo77** [comment]
예상결과물은 기존 사용시간 제한 프로그램 UI를 참고해서 만들어주시면 되고, 위에 그래프 출처 남겨주세요

**Comment by ByeongJun-Jang** [comment]
![66](https://user-images.githubusercontent.com/85213981/190843978-09975640-c048-4f39-a63b-4db8d1e35344.jpg)

**Comment by ByeongJun-Jang** [comment]
https://www.segye.com/newsView/20220406508072

**Comment by kgeunwo77** [comment]
처음 문제 정의 부분에서 그래프 내용 뒷받침할 만한 뉴스 기사나, 최근에 발생한 사건 다룬 내용 같은 거 있으면 좋을 거 같고
해결 방법 부분에서 순서도를 넣으면 좋을 거 같아서 간략한 알고리즘 생각해봅시다
그리고 기존 프로그램과의 차별성을 나타낼 수 있는 사진 하나 더 필요합니다

**Comment by ByeongJun-Jang** [comment]
https://www.segye.com/newsView/20220406508072
코로나 19관련으로 인한 청소년 게임 과몰입 이슈
