### ISSUE TITLE
Kill Process 방식

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#20]
이 기능은 근우가 구현하기로 한 부분인데, 혹시 Process를 kill할 때, PID로 하나요 아니면 name으로 하나요??

**Comment by Hong-JinSuk** [comment]
제가 process pid는 PID라는 리스트에 넣어놨습니다. 참고해서 kill process 코드 짜주시면 감사하겠습니다.

**Comment by kgeunwo77** [comment]
네 PID 리스트 참고하여 그걸 활용할 수 있는 방향으로 설계해보도록 하겠습니다.

**Comment by Hong-JinSuk** [comment]
넵~ 알겠습니다!
