### ISSUE TITLE
웹 개발 or 프로그램 개발

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#21]
원래는 Pyscript로 개발을 목표로 하고 있었는데, 문제가 생겨서 미루게 되었는데, 추후에 계속 개발하게 된다면 웹으로 할 것인지 프로그램으로 할 것인지, 웹으로 개발하고 프로그램으로 바꿀 것인지 결정해야 되는데, 어떻게 하는게 좋을지 의견좀 내주세요.

**Comment by ByeongJun-Jang** [comment]
웹으로 하게 된다면 #18 이슈에서 말씀하신 pyflask 혹은 pyqt를 이용해 하는 것인가요

**Comment by Hong-JinSuk** [comment]
웹은 flask 프로그램은 pyqt로 할려고 합니다.

일단 만들어 놓은 html과 py 코드들을 사용하기 위해서 flask를 간단하게 짜봤는데, 추후에 올려보도록 하겠습니다.

**Comment by Hong-JinSuk** [comment]
일단은 flask를 이용해서 웹으로 하는쪽으로 하는게 좋을 것 같습니다. 추후에 코드를 올려보도록 하겠습니다.
