### ISSUE TITLE
Flask를 이용한 웹 개발

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#22]
저희가 Flask로 추후에 웹 개발을 한다면, 코드는 branch를 따로 만드는게 좋을까요? 아니면 main branch에 올려놓는게 좋을 것 같습니까??

**Comment by kgeunwo77** [comment]
main에서 같이 하는 것도 좋아 보이는데, 두드러지는 차이점이 있을까요?

**Comment by Hong-JinSuk** [comment]
main에서 하다가 오류가 발생하거나 merge시에 오류 발생시 수정하기 힘들다고 하여 브런치를 따로 만들었습니다!!
