### ISSUE TITLE
현재 구현된 코드 병합

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#23]
코드를 병합해서 main.py로 올려야 될 것 같은데, 파라미터랑 함수를 어떤 방식으로 맞출까요??

**Comment by kgeunwo77** [comment]
한 명의 코드에 통일해서 같은 방식으로 맞추는 게 좋을 것 같습니다.

**Comment by Hong-JinSuk** [comment]
그럼 제가 플라스크 브런치에 조금씩 올려보겠습니다.
