### ISSUE TITLE
시간설정 이 후에 이벤트 호출관련 오류

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#24]
![시간설정 오류](https://user-images.githubusercontent.com/85213981/205429923-3ebc45db-c4c1-443d-8814-e1fd887c5319.gif)
<br>
사용자 시간 설정 후 
~~~
<form action="">
<div class="inputs">
                <div class="field">
                    <input id="user" type="number" placeholder="사용자 번호 입력" min="1">
                    <p>번 사용자 시간 설정 </p>
                </div>
                <div class="time">
                    <div>
                        <input id="hour" type="number" placeholder="0~12"  min="0" max="12">
                        :
                        <input id="min" type="number" placeholder="0~59"  min="0" max="59">
                        
                    </div>
                </div>
            </div>
            <div class="start">
                <div class="btn_wrap">
                    <div class="result_pt">
                        <button class="start_btn" input type="submit">시간 설정하기</button>    
                    </div>
                    
                </div>
            </div>
</form>
~~~
result_pt 부분에 출력하고자 하지만, js사용 미흡으로 이벤트 호출이 되지 않습니다. <br>
이를 해결하고자 묻고 싶은데 이벤트 호출 잘 사용하시는 분 있으신가요?

**Comment by Hong-JinSuk** [comment]
버튼을 눌렀을 때, addEventListener() 같은 함수로 호출 하는건 안될까요?

**Comment by ByeongJun-Jang** [comment]
> 버튼을 눌렀을 때, addEventListener() 같은 함수로 호출 하는건 안될까요?

지금 참고하여 해보겠습니다.

**Comment by ByeongJun-Jang** [comment]
![시간설정 알림](https://user-images.githubusercontent.com/85213981/205431936-072fb4df-47a8-4a94-ac17-e560519527c4.gif)
시간 설정 후 스크립트로 알림까지는 가능했습니다.

**Comment by ByeongJun-Jang** [comment]
![시간설정 알림](https://user-images.githubusercontent.com/85213981/205432024-b1494e1c-ff37-40b3-a565-07d59e3e5e5d.gif)
일단 시간 설정 후 스크립트로 알림까지는 완료하였습니다.

**Comment by kgeunwo77** [comment]
실제 데이터베이스에 입력까지 되는 것인가요?

**Comment by ByeongJun-Jang** [comment]
> 실제 데이터베이스에 입력까지 되는 것인가요?

아닙니다. 데이터베이스는 미쳐 하지 못 하였습니다
