### ISSUE TITLE
파라미터 및 변수 이름

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#29]
탐색하는 프로세스 이름( 게임이름 ) : process_name
탐색하여 찾은 프로세스 List이름 : List
List에서 process id만 따로 모아놓은 List : PID

입니다.

**Comment by kgeunwo77** [comment]
확인했습니다
List는 다른 변수와 헷갈리지는 않겠죠?

**Comment by Hong-JinSuk** [comment]
네 저는 겹치는 코드는 딱히 없을 것 같습니다.

**Comment by ByeongJun-Jang** [comment]
넵 확인했습니다

**Comment by Hong-JinSuk** [comment]
다른 변수가 생기면 업데이트해서 새 issue로 추후에 올리겠습니다.
