### ISSUE TITLE
플라스크 관련...

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#30]
![image](https://user-images.githubusercontent.com/86042721/205875038-d8529f8e-83b2-41e6-bae8-4908e90356f0.png)

위 사진과 같이 코드가 제대로 안되는데,,, 내일 저녁 전까지 해결하지 못하면 일단 연동은 미뤄두는 것으로 하겠습니다 ㅠㅠ

**Comment by ByeongJun-Jang** [comment]
파이썬 코드 공유 가능한가요?? 한번 시도해보겠습니다.

**Comment by Hong-JinSuk** [comment]
저장 과정에서 실수해서 안된 것으로 되었습니다...
