### ISSUE TITLE
process kill 하는 방식

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#35]
process name을 찾아서 pid를 가져오고 해당 프로세스를 종료시키려 하는데 이 방식 어떤가요?
process name은 겹치는 경우가 있나요?

**Comment by Hong-JinSuk** [comment]
네 process name 은 겹칠 수가 있습니다. PID는 겹치는 경우가 없으니 PID로 하는게 좋을 것 같습니다.

**Comment by kgeunwo77** [comment]
네 그럼 pid로 프로세스 식별 후 종료시키는 방향으로 하겠습니다
