### ISSUE TITLE
process kill 자식 프로세스

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#37]
for child in parent.children(recursive=True):
        child.kill()
parent.kill()

process kill할 때 위처럼 딸려있는 자식 프로세스들을 모두 종료시키고
마지막에 해당 프로세스를 종료시키려하는데 이런 방식에서 문제점이 있을까요?

**Comment by Hong-JinSuk** [comment]
문제될건 없어보이는데 처음부터 부모 프로세스를 종료해도 되지 않나요??

**Comment by kgeunwo77** [comment]
자식 프로세스가 있는 상태에서 부모만 종료되면 자식은 종료되지 않고 그대로 남아서,
자식 프로세스를 모두 종료시키고 이후 부모 프로세스도 종료시켜야할 것 같습니다

**Comment by kgeunwo77** [comment]
추가로 다른 의견 있으신가요??

**Comment by Hong-JinSuk** [comment]
하나만 종료시키고 안된다면, 부모-자식 프로세스를 모두 종료시키는 방법으로 하는건 어떨까요??

**Comment by kgeunwo77** [comment]
네 고려해보겠습니다!
