### ISSUE TITLE
Set time, Meeting and Checking

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#4]
* 역할 배분 - 일정 내로 다 할만한지
* VScode로 작성시 UI랑 C++ 코드랑 연동할만한지
* 기타 에로사항

등을 정해야 될 것 같은데, 중간 모임날짜는 수요일 12시~16시 사이로 정했으니, 각자 위 내용에 대해서 댓글 달아주시고 준비해서 와주십쇼

**Comment by kgeunwo77** [comment]
역할 배분은 지금 적당한 거 같고, 본인 맡은 파트 구현 끝내면 그때 기능 추가하는 걸로 해요
UI랑 C++코드 연동은 만나서 회의를 통해 결정하는 걸로 합시다

**Comment by ByeongJun-Jang** [comment]
프로그램을 관리하는 관리자(부모님)의 같은 경우는 첫 실행 시에 회원가입을 하여 유저마다 다르게 구별하는게 좋을 것 같아요

**Comment by Hong-JinSuk** [comment]
그럼 이제 시험기간이니깐 맡은 부분 구현만 각자 하는걸로하고 시험기간 끝나면 합쳐보는걸로 하죠~!

**Comment by ByeongJun-Jang** [comment]
> 프로그램을 관리하는 관리자(부모님)의 같은 경우는 첫 실행 시에 회원가입을 하여 유저마다 다르게 구별하는게 좋을 것 같아요

관리자 특정하는 건 회원가입 시 DB에 인풋한 결과로 정하는게 좋을거 같네 이러면 사용자 인증 측면도 원활하게 될듯하네요
