### ISSUE TITLE
kill process 방식에서 process name vs process id

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#41]
프로세스 식별할 때 이름으로 식별하면 프로세스 종료가 정상적으로 되는데,
PID로 식별하면 정상적으로 종료가 되지 않습니다
PID의 타입이 int나 char가 아니어서 그런 거 같은데 혹시 PID의 타입 아시나요?
코드 통합 시 일치시키면 해결될 거 같습니다

#이 부분
if processName == "notepad.exe":        #성공
if processName == 7662:                       #실패

**Comment by ByeongJun-Jang** [comment]
pid 타입이 char아닌가요??
타입을 string으로 하면 왠지 될 것 같아요

**Comment by Hong-JinSuk** [comment]
psutill에서 받아오는 pid의 type형은 int는 아닌걸로 알고 있습니다. str(process.pid) 형식으로 문자형을 바꿔줘야 합니다.
