### ISSUE TITLE
kill process 병합오류

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#45]
코드 부분에서

6번째 줄에서 List[i]=i 부분에서 오류가 발생합니다.

for i in PID:
    List[i]=i 부분인데, 이런식으로하면 List의 index에 pid가 들어가면서 이상한 주소가 들어가는 것 같습니다.

**Comment by kgeunwo77** [comment]
아 이해했습니다
List[i]==i
이렇게 하면 List에 PID의 숫자가 들어가니 오류가 생긴 거 같습니다
PID말고 인덱스가 들어가도록 수정하겠습니다

**Comment by Hong-JinSuk** [comment]
수정한 코드 정상적으로 작동하는거 확인하였습니다~!!
