### ISSUE TITLE
변수 이름

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#46]
List가 name이랑 PID 모두 모아놓은 것인가요?
실행 중인 프로세스의 전체 PID와 종료시켜야하는 PID가 서로 다른 변수에 각각 저장되어 있나요?

프로세스를 종료시키려면 전체 PID 리스트에서 target PID만 골라내어 종료시켜야해서 정확한 변수 이름이 필요합니다

**Comment by Hong-JinSuk** [comment]
넵 List는 name과 PID모두 있는 리스트입니다.
PID가 process.pid 정보만 받아놓은 리스트입니다.
