### ISSUE TITLE
readme의 실행 방법에 관하여

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#47]
프로젝트 초반에 작성한 readme 내용을 보충해야 할 것 같습니다.  실행과정은 로그인 -> 순으로 사진으로 표현하면 좋을 것 같은데 따로 의견있나요?

**Comment by kgeunwo77** [comment]
좋습니다. 핵심 실행화면을 순서 고려해서 사진으로 보여주면 좋을 것 같습니다.

**Comment by Hong-JinSuk** [comment]
Demo 칸에 넣으면 될 것 같습니다.

**Comment by ByeongJun-Jang** [comment]
확인했습니다 !
