### ISSUE TITLE
관리자 메인 페이지에 관하여

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#48]
<h3>현재 관리자가 시간을 설정하는 부분만 있습니다. <br>그래서 생각한 건데 메인 페이지를 구현해 메뉴바를 만들어 탭으로 이동하게 끔 하려고 하는데 어떻게 생각하시나요?</h3>
<img width="520" alt="KakaoTalk_Photo_2022-12-09-19-21-51" src="https://user-images.githubusercontent.com/85213981/206680420-7888e8a7-7578-405a-8ef2-9a35516a5b3c.png">
현재 대략 만든 것입니다.

**Comment by kgeunwo77** [comment]
시간 통계 기능 좋은 것 같습니다. 여유가 있을 시 추가하려고 했던 부가 기능인데, 탭으로 이동하는 방식도 괜찮은 거 같습니다

**Comment by Hong-JinSuk** [comment]
추후에 시간관련 통계는 파이썬으로 짜서 플라스크로 나타내보도록 해보겠습니다.

**Comment by ByeongJun-Jang** [comment]
넵 반영하여 수정했습니다 !
