### ISSUE TITLE
시간 확인 방법

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#49]
사용 시간이 설정된 제한 시간보다 커질 경우, 게임 프로세스를 종료하는 메소드를 실행시키려 합니다
이때 사용 시간이 제한 시간보다 커짐을 감지하기 위해서 무한루프를 이용하려 하는데
더 좋은 방법이 있을까요?

**Comment by Hong-JinSuk** [comment]
Threading 기법으로하면 될 것 같습니다.

**Comment by ByeongJun-Jang** [comment]
> Threading 기법으로하면 될 것 같습니다.

동일하게 생각합니다 !

**Comment by kgeunwo77** [comment]
고려해보겠습니다! 우선은 한 가지 프로세스에 대해 구현하고 이후 추진하는 방향으로 개발하겠습니다
