### ISSUE TITLE
동시에 두 게임 프로세스

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#50]
동시에 두 게임 프로세스가 실행 중인 케이스는 어떻게 처리하는 게 좋을까요?
두 개 이상의 프로세스에 관해 모두 확인해야할까요?

**Comment by Hong-JinSuk** [comment]
일단은 한개 게임일 때, 종료하고 그 다음 종료하는식으로 하면 어떨 것 같나요?

**Comment by kgeunwo77** [comment]
네 우선 프로세스 한 개에 대하여 우선적으로 구현하겠습니다

**Comment by ByeongJun-Jang** [comment]
동시에 2개 케이스가 시간 관련해서 말씀하시는 거면 카운트를 한개 기반으로 하는 게 좋을 것 같아여

**Comment by kgeunwo77** [comment]
넵 한 개만 체크하는 방식으로 하겠습니다
