### ISSUE TITLE
사용 시간과 제한 시간이 같을 경우

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#51]
사용 시간과 제한 시간이 같을 경우 (사용 시간 == 제한 시간) 어떻게 처리하는 게 좋을까요

우선 (사용 시간 > 제한 시간) 일 때 프로세스 종료 함수를 호출하도록 했는데,
사용 시간과 제한 시간이 같은 1분 동안은 어느 경우로 분류하는 것이 좋을까요?

**Comment by Hong-JinSuk** [comment]
사용시간과 제한시간이 같을 때, 종료시키는 방향으로 만드는게 좋아보입니다.

**Comment by ByeongJun-Jang** [comment]
사용 시간과 제한 시간이 같을 경우 오류가 발생하는 건가요?? 전 같을 때 종료시키는 게 좋을 것 같아요

**Comment by kgeunwo77** [comment]
오류가 발생하는 것은 아니고 기준을 명확히 정하기 위함이었습니다
의견 감사합니다 반영하겠습니다
