### ISSUE TITLE
서로 다른 사용자에 대한 정보 저장

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#52]
저희가 user1, user2, user3, ... 처럼 사용자를 구분하여 구현하는 것을 목표로 했는데,
각각의 사용자에 대한 정보를 저장할 때 하나의 데이터프레임에 저장하는 것이 좋을까요,
아니면 사용자마다 따로 정보를 저장하는 df가 있는 것이 좋을까요?
아래는 하나의 df로 만든 모습입니다

`df=pd.DataFrame([[0,120],
                 [0,60],
                 [0,30]],
               index=['user1','user2','user3'],
                columns=['사용시간','제한시간'])`

**Comment by Hong-JinSuk** [comment]
데이터프레임이 괜찮아 보입니다!

**Comment by ByeongJun-Jang** [comment]
우선 데이터프레임으로 하는 게 좋아보입니다

**Comment by kgeunwo77** [comment]
네 그럼 하나의 데이터프레임에 통합해서 저장하는 방식을 사용하겠습니다.
