### ISSUE TITLE
게임 프로세스 실행 중인지 판단하는 함수 결과값

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#56]
게임 프로세스가 실행 중인지 아닌지 판단하는 함수에서 True/False로 결과가 도출되나요?
함수의 결과가 조건문의 조건으로 사용할 수 있는 값인지 궁금합니다

**Comment by Hong-JinSuk** [comment]
현재 True/Fasle로 하고 있습니다.

**Comment by kgeunwo77** [comment]
넵 확인했습니다
