### ISSUE TITLE
관리자 페이지에서 시간 통계에 관하여

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#59]
관리자 페이지에서 시간 통계에 관하여 js 를 활용해 사용자 별 요일별로 시각화하려고 합니다.  괜찮은 아이디어 있나요?

**Comment by kgeunwo77** [comment]
사용자별로 그날 할당 받은 제한 시간을 모두 사용했는지, 남았는지
남았으면 얼마나 남았는지 계산해서 보여주면 좋을 거 같습니다

평균적인 컴퓨터 이용 시간을 일주일 단위로 통계를 내서 보여주면 좋을 거 같습니다
ex) 일 평균 (?) 시간 (?) 분 사용

**Comment by ByeongJun-Jang** [comment]
> 사용자별로 그날 할당 받은 제한 시간을 모두 사용했는지, 남았는지 남았으면 얼마나 남았는지 계산해서 보여주면 좋을 거 같습니다
> 
> 평균적인 컴퓨터 이용 시간을 일주일 단위로 통계를 내서 보여주면 좋을 거 같습니다 ex) 일 평균 (?) 시간 (?) 분 사용

네 확인했습니다 !

**Comment by Hong-JinSuk** [comment]
통계는 누적 그래프와 당일 그래프로 하면 좋을 것 같습니다!

**Comment by ByeongJun-Jang** [comment]
해결하였기에 이슈는 닫겠습니다 !
