### ISSUE TITLE
to_csv 했을 때 한글 깨지는 상황

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#6]
df.to_csv('C:/Users/Agwoo/Desktop/새 폴더/07.csv',header='False')

이대로 csv 파일 생성하면 열었을 때 한글이 깨져요

**Comment by Hong-JinSuk** [comment]
window 환경에서는 encoding='cp949' 하면 됨됨~
쥬피터면 UTP-8
