### ISSUE TITLE
Threading 기법 한계

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#60]
현재 Threading 기법으로 개별로 실행하였을 때는, 문제가 없는데, 코드를 병합하고 실행하니 Thread buffer에서 문제가 발생하였습니다. 추후에 Multiprocessing 기법으로 하면 될 것 같은데 시간상 Multiprocessing까지는 힘들 것 같습니다.

**Comment by kgeunwo77** [comment]
그러면 우선 multiprocessing은 시작하지 맙시다
threading 기법을 사용하지 못하면 여러 프로세스를 병렬로 체크하는 것이 불가능한 건가요?

**Comment by Hong-JinSuk** [comment]
일단 이번 프로젝트는 threading 기법으로 마치겠습니다.
