### ISSUE TITLE
게임 중인지 확인하는 시간 간격

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#61]
사용자가 현재 게임 중인지 모니터링을 하는데,
정해진 시간 간격으로 예를 들어 1분 마다 확인을 한다 이런 방법이 있고

아니면 무한루프를 이용해서 스핀락 방식으로 게임이 종료할 때까지 계속 대기하는 방법이 있습니다

어떤 것이 더 나을까요?

**Comment by Hong-JinSuk** [comment]
제 코드는 일단 무한루프와 sleep 함수를 이용해서 구현했습니다.

**Comment by kgeunwo77** [comment]
확인했습니다!
