### ISSUE TITLE
mainFlask 최종 pull request

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#67]
시간상 게임을 켰을 때, 시간이 지나고, 시간이 다 되면 프로세스를 강제종료 시키는 선까지는 완료했지만, 다른 기능은 완벽하게 연동하지 못했습니다.

확인해주시고 Merge해주세요

**Comment by kgeunwo77** [comment]
확인하고 merge 했습니다~
