### ISSUE TITLE
연동 정도

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#68]
Check_process : 완료
Find_process name & pid : 완료
Check memory Usage : 완료
kill process : 완료

Flask 및 UI : 미완
Database : 미완

UI와 DB의 경우 추후에 가능하다면 계속하는 것으로 할까요?

**Comment by kgeunwo77** [comment]
좋아요 DB 연동은 가능할 것으로 보입니다

**Comment by ByeongJun-Jang** [comment]
넵 ui는 사용자한테 보여 줄 것을 보완하면 될 것 같습니다

**Comment by Hong-JinSuk** [comment]
넵 알겠습니다!
