### ISSUE TITLE
추가 기능) 알람 기능 추가 어떠신가요

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#7]
피시방처럼 남은 시간이 10분일 때 사용자에게 알려주는 알람 기능 추가하는 거 어떠세요?
만약 한다면 시스템 경고처럼 알림창을 띄울건지 아니면 그냥 화면에 그림처럼 띄울건지도 생각해주세요

**Comment by Hong-JinSuk** [comment]
일단 하던기능 구현하고 연동까지하면 좋은 아이디라고 생각함돠

**Comment by ByeongJun-Jang** [comment]
> 피시방처럼 남은 시간이 10분일 때 사용자에게 알려주는 알람 기능 추가하는 거 어떠세요? 만약 한다면 시스템 경고처럼 알림창을 띄울건지 아니면 그냥 화면에 그림처럼 띄울건지도 생각해주세요

사용자가 직접인지 할 수 있도록 경고음도 발생하는 것도 좋을 것 같아요

**Comment by Hong-JinSuk** [comment]
그럼 근우가 하던거 다 끝나면 추가기능까지 구현해서 합쳐보는 것으로 하죠!
