### ISSUE TITLE
추가 기능 중 알림 기능 구현

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#73]
버튼 눌러서 나오는 방식으로 구현을 해보았는데,
버튼 누르지 않고 바로 알림창을 띄우는 방식이 더 좋을까요?

**Comment by ByeongJun-Jang** [comment]
시간 알림 관련인가요??  저는 반응형으로 나오는 것보다 알림창이 나타나는 게 좋을 것 같습니다 !

**Comment by kgeunwo77** [comment]
확인했습니다 알림창 띄우는 방식으로 해보겠습니다
