### ISSUE TITLE
기말 발표에 관하여

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#74]
### 기말 발표를 다가오는 12일에 진행합니다.
![image](https://user-images.githubusercontent.com/85213981/206854216-4341abe9-9a0a-4279-92d9-7219acbdebe0.png)

### 추가할 내용 있으면 말씀해주세요 !

**Comment by kgeunwo77** [comment]
결과물에 계획대비, 완성도 두 항목이 있는데 각각 어떤 내용이 들어가야할지 생각해봐야할 것 같습니다
계획대비는 전에 만들었던 ppt 자료를 참고하고, 완성도는 최종 결과물을 보여주는 것이 어떨까요?

**Comment by ByeongJun-Jang** [comment]
> 결과물에 계획대비, 완성도 두 항목이 있는데 각각 어떤 내용이 들어가야할지 생각해봐야할 것 같습니다 계획대비는 전에 만들었던 ppt 자료를 참고하고, 완성도는 최종 결과물을 보여주는 것이 어떨까요?

네 반영하겠습니다 !

**Comment by Hong-JinSuk** [comment]
넵 발표관련 내용 찾아보겠습니다~!

**Comment by ByeongJun-Jang** [comment]
네 확인했습니다 !
