### ISSUE TITLE
남은 시간 10분일 때 알람

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#77]
`
if remain==10:
    win32api.MessageBox(0, "10분 남았습니다.", "알림", 48)
`
조건문의 조건이 잘못된 것인지, 오류가 발생했습니다. 조건문이 제대로 작동하지 않습니다. 이유 아시는 분 있을까요?

**Comment by ByeongJun-Jang** [comment]
함수가 어떻게 되는지 알 수 있을까요?

**Comment by Hong-JinSuk** [comment]
dataframe에서 가져온 값이 int형이 아닌 것 같습니다. 제가 이러한 부분은 잘 몰라서 정확하게 답변해드릴 수는 없을 것 같습니다.

**Comment by kgeunwo77** [comment]
> 함수가 어떻게 되는지 알 수 있을까요?

우선 데이터프레임에서 사용시간과 제한시간을 가져온 뒤 잔여 시간을 계산하고 이 잔여 시간이 10분일 경우를 뜻하는 조건문입니다

**Comment by kgeunwo77** [comment]
> dataframe에서 가져온 값이 int형이 아닌 것 같습니다. 제가 이러한 부분은 잘 몰라서 정확하게 답변해드릴 수는 없을 것 같습니다.

타입 문제가 맞는 거 같습니다 수정해보겠습니다
