### ISSUE TITLE
알림 코드 연동 문제

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#78]
현재 알림창 띄우는 코드를 완성했는데, 어느 부분에 병합해서 추가하는 것이 좋을까요?
좋은 의견 있으면 남겨주세요

**Comment by ByeongJun-Jang** [comment]
유저인터페이스에 병합하는 것이 좋은 것 같습니다 !

**Comment by kgeunwo77** [comment]
의견 감사합니다. 유저인터페이스 쪽과 check_time 쪽으로 고려해보겠습니다.
