### ISSUE TITLE
사용자의 수 문제

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#79]
정보를 저장하기 위한 데이터프레임을 처음 생성할 때
현재는 user1, user2, user3 이렇게 각기 다른 세 명의 유저의 공간을 만들었습니다

사용자가 세 명 이상인 경우엔 어떻게 하는 것이 좋을까요?
사용자의 수에 따라 유동적으로 데이터베이스를 관리할 수 있는 방법이 필요합니다

**Comment by Hong-JinSuk** [comment]
나중에 동적할당처럼 동적으로 만들 수 있는 방법을 찾아보죠!

**Comment by ByeongJun-Jang** [comment]
데이터베이스를 활용한다면 유저 회원가입 시 테이블 추가하는 것이 좋아보입니다

**Comment by kgeunwo77** [comment]
파일시스템의 한계인 거 같습니다. 동적할당 방식도 고려해보겠습니다.
