### ISSUE TITLE
How to interface with UI 

### ISSUE THREAD

**Issue by Hong-JinSuk** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#8]
# 우리가 C++로 하는중인데, UI랑 연동할려면 python으로 짜야될 것 같은데 다들 어떻게 생각하시나요??

**Comment by kgeunwo77** [comment]
같은 언어로 할 수 있는 부분은 python으로 통합해서 하는 것이 좋을 것 같습니다

**Comment by ByeongJun-Jang** [comment]
> # 우리가 C++로 하는중인데, UI랑 연동할려면 python으로 짜야될 것 같은데 다들 어떻게 생각하시나요??

html로 연동에 관하여 조사해봤는데 [https://www.youtube.com/watch?v=3DuyJf_XPtM&t=110s](url) 관련된 정보가 있습니다. 연동관련해선 크게 문제 되는 점 없을 것 같습니다.

**Comment by Hong-JinSuk** [comment]
그럼 Python으로 기능 구현을 하고, Pyscript로 합쳐보는 걸로 하죠!!
