### ISSUE TITLE
Timedelta

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#80]
이전에도 데이터프레임에 입력된 시간 값의 타입에 관한 이슈가 있었는데요
timedelta 함수를 사용하여 보기 편하게 00:00:00 형식으로 표현해서 그런 것 같습니다
함수를 사용하지 않고 분 단위의 int 형으로 그대로 표현하는 것이 더 나은 선택일까요?
timedelta 함수를 사용하면 보기엔 편하지만 값을 읽어올 때마다 int형으로 변환해야하는 번거로움이 있습니다.

**Comment by ByeongJun-Jang** [comment]
분 단위의 데이터로 하는 편이 좋아보입니다 ! 관리자에게 제공하는 시간 통계도 분 단위로 표현했기 때문입니다 !

**Comment by kgeunwo77** [comment]
네 반영하겠습니다!
