### ISSUE TITLE
남은 시간 시각화 모양

### ISSUE THREAD

**Issue by kgeunwo77** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#81]
이전 계획은 사용자 컴퓨터 화면 한쪽에 작은 UI를 띄워서 남은 제한 시간을 확인할 수 있도록 하는 것이었습니다
이것 대신에 사용시간/제한시간 비율을 퍼센트로 보여주는 UI로 대체하여 코드를 작성했는데 어떠신가요?
좋은 아이디어 있으면 써주세요

**Comment by ByeongJun-Jang** [comment]
남은 시간을 점점 채워나가는 건가요?? 좋은 아이디어 같아요 ! 남은 시간을 알려주는 것보다 보기 편한 것 같아요 !

**Comment by kgeunwo77** [comment]
네 스마트폰 배터리 잔량 표시 같은 느낌입니다. 의견 감사합니다
