### ISSUE TITLE
중간 발표 준비에 관하여

### ISSUE THREAD

**Issue by ByeongJun-Jang** [Hong-JinSuk/CBNU-Industry_Project3-2-Team#9]
<h2>먼저 생각해야할 부분</h2>

1.Solution

2.멘토링 결과에 대하여 주제에 어떤 변화가 있었는지

3.개발 일정

4.평가 플랜(아직 미정으로)

-----------------------

이에 관하여 이번주 목요일 10/20(목)까지 생각하여 저녁시간 이 후에 ppt완성을 목표로 얘기해보죠

**Comment by Hong-JinSuk** [comment]
멘토링 결과에 대해서는 제가 정리하고 올린게 있으니 제가 하는게 어떨까용

**Comment by kgeunwo77** [comment]
좋아요 그럼 나머지 개발 일정은 제가 따로 이슈 만들어 놓을테니 그곳에 의견 남겨주시면 좋을 거 같아요
대략적으로 현재 각자 맡은 파트 9주차까지 끝내는 걸 목표로 하고 9주차부터 일정 짜겠습니다

**Comment by ByeongJun-Jang** [comment]
> 좋아요 그럼 나머지 개발 일정은 제가 따로 이슈 만들어 놓을테니 그곳에 의견 남겨주시면 좋을 거 같아요 대략적으로 현재 각자 맡은 파트 9주차까지 끝내는 걸 목표로 하고 9주차부터 일정 짜겠습니다

네 알겠습니다. 전 solution에 해당하는 파트를 정리해 이슈로 등록하겠습니다. 앞서 작성할 이슈에 개발 현황을 커멘트 달아주시면 감사하겠습니다.
